catalogMode: prefer

shellEmulator: true

trustPolicy: no-downgrade

packages:
  - packages/*
  - apps/*

catalogs:
  build:
    tsdown: ^0.19.0
  eslint:
    '@antfu/eslint-config': ^7.0.0
    eslint: ^9.39.2
    eslint-plugin-format: ^1.3.1
  testing:
    vitest: ^4.0.17
  types:
    '@types/node': ^25.0.8
  typescript:
    tsx: ^4.21.0
    typescript: 5.8.3
  utils:
    execa: ^9.6.1
    lint-staged: ^16.2.7
    simple-git-hooks: ^2.13.1
  vite:
    vite: ^7.3.1
